# Generated by Django 5.2.5 on 2025-08-27 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Passport Number"
                    ),
                ),
                (
                    "passport_expiry_date",
                    models.DateField(verbose_name="Passport Expiry Date"),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nationality"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outgoing", "Outgoing"), ("incoming", "Incoming")],
                        default="outgoing",
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        help_text="e.g., 'New Booking Onboarding Workflow'",
                        max_length=255,
                        verbose_name="Triggered By",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_logs",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Log",
                "verbose_name_plural": "Communication Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport_copy", "Passport Copy"),
                            ("personal_photo", "Personal Photo"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="customer_documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("uploaded", "Uploaded"),
                            ("verified", "Verified"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
