# Generated by Django 5.2.5 on 2025-08-27 00:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Trip Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("departure_date", models.DateTimeField(verbose_name="Departure Date")),
                ("return_date", models.DateTimeField(verbose_name="Return Date")),
                (
                    "total_seats",
                    models.PositiveIntegerField(verbose_name="Total Seats"),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per Person"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "hotel_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Hotel Details"
                    ),
                ),
                (
                    "flight_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Flight Details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["departure_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date of Expense",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date"],
            },
        ),
    ]
