# Generated by Django 5.2.5 on 2025-08-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("flights", "Flight Tickets"),
                    ("hotel", "Hotel Booking"),
                    ("transport", "Transportation"),
                    ("visa", "Visa Fees"),
                    ("catering", "Catering"),
                    ("marketing", "Marketing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(
                help_text="Provide a specific description for this expense.",
                max_length=255,
                verbose_name="Description",
            ),
        ),
    ]
