# Generated by Django 5.2.5 on 2025-08-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_expense_category_alter_expense_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("flights", "Flight Tickets"),
                    ("hotel", "Hotel Booking"),
                    ("transport", "Transportation"),
                    ("visa", "Visa Fees"),
                    ("catering", "Catering"),
                    ("marketing", "Marketing"),
                    ("other", "Other (Specify)"),
                ],
                default="flights",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Required only if category is 'Other'.",
                max_length=255,
                verbose_name="Description",
            ),
        ),
    ]
