# Generated by Django 5.2.5 on 2025-08-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_alter_expense_category_alter_expense_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
    ]
